services:
  tmisapp:
    container_name: tmisFeContainer
    build:
      context: ./Frontend_Angular
      dockerfile: Dockerfile
    image: tmisapp
    ports:
      - "80:80"
    networks:
      - internalnet  # Use the defined internal network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./Frontend_Angular:/app

  springbootapp:
    container_name: springbootContainer
    build:
      context: ./Java-Backend
      dockerfile: Dockerfile
    image: springbootapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/talentmanagement?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password
      SPRING_PROFILES_ACTIVE: prod
      SERVER_ADDRESS: 0.0.0.0
    depends_on:
      - mysql
    networks:
      - internalnet  # Use the defined internal network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    secrets:
      - db_password
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  mysql:
    image: mariadb:latest
    container_name: mysqlContainer
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: talentmanagement
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internalnet  # Use the defined internal network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    secrets:
      - db_root_password
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  internalnet:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt

volumes:
  mysql_data:
    driver: local
